const quotes = [
  "Growth begins at the end of your comfort zone.",
  "Every new dawn is an opportunity to rewrite your story.",
  "In life’s symphony, setbacks are merely unexpected notes.",
  "To see the rainbow, sometimes we must endure the rain.",
  "Embrace the unknown, for it holds uncharted wonders.",
  "The beauty of life is woven in its unpredictability.",
  "Where words fail, actions speak; where actions fail, heart speaks.",
  "Moments of solitude often lead to bursts of clarity.",
  "Adventures are the best way to learn the map of life.",
  "The heart's whispers often hold the loudest truths.",
  "In every shadow, there's light waiting to break through.",
  "The power of a dream lies not in its size but in its vision.",
  "An open mind is the doorway to boundless possibilities.",
  "We grow not by clinging to the past, but by embracing the present.",
  "Your worth is not determined by the world but by your own beliefs.",
  "The tapestry of life is richest when woven with varied threads.",
  "Life doesn't give us what we want, but what we need to grow.",
  "The compass of the heart always points towards love.",
  "In the garden of existence, nurture the flowers, not the weeds.",
  "The best view often comes after the hardest climb.",
  "Cherish the detours; they often lead to the most beautiful destinations.",
  "Trust, once broken, is like a vase; even if mended, the cracks remain visible.",
  "The universe is a mirror reflecting our innermost beliefs.",
  "To find balance, sometimes we must brave the tightrope of life.",
  "Every sun must set, but it promises a new day.",
  "Real wealth is not what we accumulate, but what we radiate.",
  "Life’s melodies are sweeter when sung in harmony.",
  "Opportunities often come disguised as challenges.",
  "The most potent magic is the one we believe in.",
  "The future is a story yet to be written; make it a bestseller.",
  "Life isn't about collecting moments, but immersing in them.",
  "Where there is love, boundaries become bridges.",
  "Wisdom is the light that illuminates the path of experience.",
  "Life’s journey is not about arriving but evolving.",
  "True courage is pursuing a dream even when the path is uncertain.",
  "Our legacy is not in our possessions, but in the lives we touch.",
  "Where logic ends, faith begins.",
  "The waves of change bring treasures of wisdom ashore.",
  "Life’s richest lessons are hidden in its simplest moments.",
  "Believe in miracles, and you become the miracle.",
  "The echo of kindness lasts an eternity.",
  "Genuine leaders inspire by example, not command.",
  "Nature’s serenity is the universe’s way of whispering wisdom.",
  "Your vibe attracts your tribe.",
  "Find joy in the journey, not just the destination.",
  "Every setback is a setup for a stronger comeback.",
  "In the garden of the heart, let love bloom without restraint.",
  "A leap of faith often leads to life’s most profound discoveries.",
  "Time is the river in which moments are but fleeting ripples.",
  "The warmth of a genuine smile can melt the iciest heart.",
  "Life is not about waiting, but creating memories worth waiting for.",
  "Every ending holds the promise of a new beginning.",
  "Stars shine brightest in the darkest nights.",
  "Passion is the fuel that drives our wildest dreams.",
  "Each challenge faced is a stepping stone towards our destiny.",
  "Change is inevitable, growth is a choice.",
  "A single candle can light up a room, just as one act of kindness can illuminate a life.",
  "Fears are but shadows of our own making.",
  "The key to contentment is not in having more, but in wanting less.",
  "Adversity introduces us to ourselves.",
  "In silence, the heart speaks volumes.",
  "Dreams are the universe's way of showing us what's possible.",
  "The winds of change carry seeds of new beginnings.",
  "A purpose-driven life is a life of fulfillment.",
  "The stories we tell ourselves shape our realities.",
  "Wisdom is not in knowing everything but in understanding the essence.",
  "The journey of a thousand miles begins with a single step.",
  "In the rhythm of life, patience is the pause between notes.",
  "Hope is the beacon that guides us through our darkest nights.",
  "The art of living lies in finding beauty in the ordinary.",
  "Grit is pushing forward even when every muscle screams to stop.",
  "Challenges are life's way of testing our resolve.",
  "Grace is in accepting our flaws and loving ourselves anyway.",
  "The most profound answers often lie in the simplest questions.",
  "Time heals, teaches, and transforms.",
  "In the dance of life, it's okay to miss a step and find a new beat.",
  "Our mistakes do not define us; our responses do.",
  "True wealth is measured in moments, not material.",
  "The best stories often come from life's unexpected twists.",
  "We rise by lifting others.",
  "In the vast cosmos, our existence is a fleeting but beautiful spark.",
  "Life's symphony is a blend of highs, lows, and the notes in between.",
  "To understand life, we must first learn to embrace its mysteries.",
  "Resilience is the art of bouncing back with learned wisdom.",
  "The universe always listens; be careful of what you ask for.",
  "Curiosity is the compass that leads us to new horizons.",
  "Peace is not the absence of chaos but finding calm amidst it.",
  "The heart's capacity to love is limitless.",
  "Nature is the world's most ancient storyteller.",
  "In every goodbye, there's the promise of a new hello.",
  "Music is the soul's language, resonating across time and space.",
  "Courage is not the absence of fear but facing it head-on.",
  "In the book of life, each day is a blank page waiting for a story.",
  "Where there's will, there's a way; where there's passion, there's a blaze.",
  "A life lived in love will never be dull.",
  "Dreams are the seeds of reality.",
  "Joy is not in things; it's in us.",
  "Serenity is not freedom from the storm but peace within it.",
  "A journey of self-discovery begins with a single inward glance.",
  "Our deepest wisdom often springs from our deepest pain.",
  "Life is an echo; what you send out comes back.",
  "The best teacher in life is experience.",
  "Beauty is not in the face; beauty is a light in the heart.",
  "Gratitude turns what we have into enough.",
  "In the depths of winter, we find within us an invincible summer.",
  "The future is a canvas waiting for our brushstrokes.",
  "To touch the soul of another is to walk on sacred ground.",
  "A river cuts through rock not because of its power but its persistence.",
  "Life is a balance of holding on and letting go.",
  "Where love resides, fear cannot.",
  "In every moment, lies an opportunity to change the future.",
  "Mistakes are the portals of discovery.",
  "In the silence of the night, our deepest thoughts come to light.",
  "The soul would have no rainbow if the eyes had no tears.",
  "The strongest people are not those who show strength in front of us but those who fight battles we know nothing about.",
  "Kindness is a language that the deaf can hear and the blind can see.",
  "Every closed door isn’t locked; sometimes you just need to push.",
  "True wisdom is knowing the depth of what you don't know.",
  "In our quest for more, we must not lose sight of enough.",
  "The best memories are often made in unplanned moments.",
  "Life is a journey with problems to solve, lessons to learn, but most of all, experiences to enjoy.",
  "Harmony is when the inner song and the outer world sing the same melody.",
  "Growth and comfort do not coexist.",
  "Every smile, every word, every act of kindness, ripples through the universe.",
  "The hardest battles are given to the strongest soldiers.",
  "The universe dances to the rhythm of our heartbeat.",
  "Laughter is timeless, imagination has no age, and dreams are forever.",
  "Stars can't shine without darkness.",
  "The road less traveled often leads to the most stunning destinations.",
  "Discoveries lie not in new landscapes but in having new eyes.",
  "Each sunrise offers a chance to hit the reset button on our lives.",
  "Behind every adversity lies an opportunity waiting to be seized.",
  "Life's true essence lies in the imperfections, not the perfections.",
  "To be free is not to have fewer chains, but to possess the power to throw them off.",
  "The mind is a garden where thoughts blossom; nurture positivity.",
  "A kind gesture can cross miles and touch hearts across the world.",
  "Time is a sculptor, shaping our experiences and carving wisdom.",
  "We do not remember days; we remember moments.",
  "When we align our actions with our passions, miracles unfold.",
  "Imagination is a force that can manifest realities.",
  "Pain is temporary; quitting lasts forever.",
  "When you can't find the light, become the light.",
  "Life isn't about finding yourself; it's about creating yourself.",
  "In the currency of time, moments spent in love are priceless.",
  "The quieter you become, the more you can hear.",
  "Wings of hope carry us, soaring high above the clouds of doubt.",
  "Cherished dreams are the seeds from which realities bloom.",
  "Embrace the journey, even if the path isn't clear.",
  "Obstacles do not block the path; they are the path.",
  "The canvas of life is waiting for your unique shade of color.",
  "In the heart's silent conversations, we find genuine truths.",
  "Your actions define your character; your words define your wisdom.",
  "Seek to be worth knowing rather than well-known.",
  "When the heart sings, the soul resonates.",
  "Opportunities are like sunrises; if you wait too long, you miss them.",
  "Memories made with love are timeless treasures.",
  "Kindness is the echo of the universe responding to love.",
  "Life begins at the end of your comfort zone's horizon.",
  "Adventure awaits those who dare to dream.",
  "In the realm of dreams, the heart finds its anchor.",
  "Limitations live only in our minds, but if we use our imaginations, possibilities become limitless.",
  "When we lift our gaze to the stars, we find our place in the universe.",
  "True success is not the destination but the journey.",
  "The stories we weave today become the legends of tomorrow.",
  "In life's grand tapestry, every thread has its purpose.",
  "With hope as your compass, navigate the seas of uncertainty.",
  // ... [previous quotes]

  "In the quiet moments, the universe whispers its secrets.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "Within nature’s silence, we hear the most profound messages.",
  "The strength of the spirit can conquer any storm of the mind.",
  "Love is the bridge between two souls and the light of existence.",
  "Every story has an end, but in life, every ending is a new beginning.",
  "The best sermons are lived, not preached.",
  "If you wish to move mountains tomorrow, start by lifting pebbles today.",
  "With each fallen sunset, the promise of a new dawn awaits.",
  "Sometimes the hardest lessons are given to the bravest students.",
  "Wise is the one who learns from another’s mistakes. Wiser is the one who learns from their own.",
  "The tree of wisdom is watered by the tears of experience.",
  "Magic exists for those who dare to look beyond the obvious.",
  "Destiny is not pre-written but handcrafted with each choice.",
  "In the symphony of existence, each one of us is a unique note.",
  "Peace is the art of subtracting the thoughts that disturb you.",
  "In the realm of possibilities, determination is king.",
  "When the roots of love are deep, there’s no need to fear the wind.",
  "Life’s richest treasures are unveiled through the heart, not the eyes.",
  "Live for the moments that take your breath away.",
  "Let your dreams be your wings, guiding you to uncharted horizons.",
  "In the puzzle of existence, every experience is a piece.",
  "Our past carves out paths for our future, but we hold the chisel.",
  "Seek not to be a person of success, but rather a person of value.",
  "Beauty is not held in the face; it is a flame in the soul.",
  "Silent gratitude isn’t much use to anyone; express it, amplify it.",
  "The best time to plant a tree was twenty years ago. The second best time is now.",
  "Genuine freedom is not in having the world, but in holding nothing.",
  "Mysteries unfold when we embrace uncertainties with an open heart.",
  "Chase dreams, not people. Attract vibes, not attention.",
  "When you dance to your own rhythm, the world marvels at your music.",
  "In the theater of life, authenticity is the best act.",
  "If the path before you is clear, you're probably on someone else's.",
  "Dive deep into the ocean of self-awareness; treasures await.",
  "The sky is not the limit; your beliefs are.",
  "Let your soul be a beacon, guiding others through the night.",
  "When hope anchors the soul, resilience sails through storms.",
  // ... [previous quotes]

  "Perseverance is the silent roar of an indomitable spirit.",
  "Life is not about waiting for the storm to pass, but learning to dance in the rain.",
  "In the depth of winter, we often discover our invincible summer.",
  "Doubt kills dreams more than failure ever will.",
  "Where words fail, the heart's silence speaks volumes.",
  "Each sunrise paints a new masterpiece on the canvas of life.",
  "The beauty of life is not in the grand moments, but in the small pauses.",
  "Truth, like gold, is often found at the depth of authenticity.",
  "Happiness is not a state to arrive at, but a manner of traveling.",
  "Behind the clouds, the sun still shines.",
  "Mountains are climbed not by strength but by perseverance.",
  "The art of wisdom is in recognizing life's simple pleasures.",
  "Where the path seems unclear, let passion be your guiding light.",
  "Fear not the unknown; it's a sea of possibilities.",
  "To live fully is to embrace both the shadows and the light.",
  "Challenges are merely detours on the path to success.",
  "In the echoes of silence, intuition whispers.",
  "The universe does not speak in words, but in synchronicities.",
  "When one door closes, countless others await discovery.",
  "The soul's fire is kindled by life's experiences.",
  "To touch a soul with kindness is to shape eternity.",
  "Beyond the horizon of fear lie the vast plains of courage.",
  "In life's grand tapestry, every thread weaves a tale of meaning.",
  "The music of life is in the spaces between the notes.",
  "Sometimes, growth is silent, and progress is invisible.",
  "Hope is not a dream but a way of turning dreams into reality.",
  "Life isn't about collecting moments, but immersing in each one.",
  "The garden of the world is rich with diverse flowers of potential.",
  "Discover the universe within; it mirrors the universe without.",
  "In the dance of existence, grace is in the steps we choose.",
  "Life's beauty is not in grand events but in unscripted moments.",
  "True strength is not in being unbreakable but in bending and not breaking.",
  "Every shadow in life is a reminder that light exists.",
  "Be like water, adaptable yet powerful in its persistence.",
  "From life's broken pieces, mosaic masterpieces are born.",
  "When the night is at its darkest, stars shine their brightest.",
  "Wander not to find yourself, but to remember who you've been all along.",
  // ... [previous quotes]

  "The symphony of life is composed of highs and lows, making it a masterpiece.",
  "Curiosity is the compass that leads us to our passions.",
  "In stillness, we find the melodies of the soul.",
  "The brightest gems are often found in the deepest mines.",
  "Our greatest growth often springs from our deepest wounds.",
  "Dream with ambition and live with purpose.",
  "In the tapestry of existence, even the tiniest threads have purpose.",
  "Every sunset is a promise of a new beginning.",
  "The most powerful tool we possess is the power of choice.",
  "In the pages of history, actions speak louder than words.",
  "Where logic ends, magic begins.",
  "The universe sings a song of harmony, waiting for us to join the chorus.",
  "A moment of patience can save a lifetime of regret.",
  "Every challenge faced in life polishes the diamond within.",
  "Life is the art of drawing without an eraser.",
  "Our lives are defined by the depth of our connections, not the length of our possessions.",
  "Trust the timing of your journey; every chapter has its purpose.",
  "The voyage of discovery is not in seeking new lands but seeing with new eyes.",
  "Where the mind believes, the heart achieves.",
  "Fulfillment is not found in the crowd but in the depth of solitude.",
  "Life's storms are nature’s way of testing the strength of our anchor.",
  "The universe conspires in our favor when we act with love and intention.",
  "Embrace change; it's the universe's way of nudging you towards growth.",
  "Each heartbeat is a universe of possibilities.",
  "The ink of introspection writes the most authentic stories.",
  "A life lived with intention is a masterpiece in motion.",
  "Adversity introduces us to our true selves.",
  "Where there's hope, there's life.",
  "Be the energy you wish to see in the world.",
  "Live not for the applause but for the purpose.",
  "The mosaic of life is complete with both light and shadow.",
  "In the galaxy of human emotions, love shines the brightest.",
  "Seek the essence of life, and the universe reveals its secrets.",
  "The language of the heart transcends borders and barriers.",
  "When the world becomes noise, find the music within.",
  "Our thoughts are the brushstrokes painting our life's canvas.",
  "In every ending lies the seed of a fresh beginning.",
  "The bridges we build often lead to the most unexpected destinations.",
  // ... [previous quotes]

  "Gaze upon the stars, and you'll see the reflection of endless possibilities.",
  "The whispers of the heart often shout the truths of the universe.",
  "Life's richness isn't counted in days, but in timeless moments.",
  "Every scar has a story, every story, a lesson.",
  "The tapestry of existence is woven with threads of time and choices.",
  "Your vibe attracts your tribe.",
  "The heart's compass always points towards love.",
  "Moments of solitude are the soul's way of catching its breath.",
  "Every challenge unraveled is a step closer to the self.",
  "In the orchestra of life, every instrument has its role.",
  "Seek less to impress, more to inspire.",
  "Life is not a race, but a rhythm.",
  "Courage is not the absence of fear, but the triumph over it.",
  "The footprints we leave in the sands of time tell stories of perseverance and hope.",
  "The most profound answers are often hidden in simple questions.",
  "Embrace the unknown; it's where the magic unfolds.",
  "Life's waves might rock our boat, but it's the set of the sail that determines our direction.",
  "Breathe in experiences, exhale wisdom.",
  "The world is a book, and those who do not travel read only a page.",
  "We rise by lifting others.",
  "Passion ignites the fire of purpose.",
  "In the garden of life, the most vibrant flowers have known adversity.",
  "The universe dances to the rhythm of our beliefs.",
  "Every tear sown is a step towards blossoming strength.",
  "It's not the load that breaks you, it's the way you carry it.",
  "To understand life, we must first live it in all its shades.",
  "Every locked door has a key; patience and persistence find it.",
  "In the silent symphony of existence, our actions are the loudest notes.",
  "Dreams are the seeds of realities yet to blossom.",
  "Find beauty not only in the thing itself but in the pattern of the shadows.",
  "The greatest secrets are always hidden in the most unlikely places.",
  "True wealth is not measured by what we have, but by what we are.",
  "With every rising sun, the universe whispers, 'Begin again'.",
  "Growth is a dance between letting go and holding on.",
  "Wisdom is the gold extracted from the ores of experiences.",
  "The mightiest rivers flow from humble beginnings.",
  "Our brightest flames are often kindled by our darkest hours.",
  "Where love dwells, miracles unfold.",
  // ... [previous quotes]

  "Life's beauty is in its unpredictability and endless possibilities.",
  "Trust the journey, even when you don't understand the path.",
  "Miracles are often found in the mundane, if only we choose to look.",
  "The wings of change are birthed from the cocoon of challenge.",
  "Where words falter, the soul's resonance remains.",
  "Embrace the detours; they often lead to the most scenic routes.",
  "The key to growth is the introduction of higher dimensions of consciousness into our awareness.",
  "Every brush with nature paints a masterpiece on the canvas of the soul.",
  "The most profound conversations are those without words, just feelings.",
  "To soar, one must first be willing to leave the ground.",
  "Real wealth is measured in moments, not just in material.",
  "Where wonder goes, energy flows.",
  "In the heart's quiet, the universe's loudest echoes are heard.",
  "To touch the infinite, dive into your inner depths.",
  "In every challenge, there's a hidden chapter waiting to be written.",
  "Time is the most valuable currency; spend it wisely.",
  "The heart knows a thousand ways to speak, even in silence.",
  "Nature teaches the art of balance, patience, and rejuvenation.",
  "The best view often comes after the hardest climb.",
  "To find yourself, sometimes you must lose yourself.",
  "Where passion thrives, boundaries dissolve.",
  "In the library of existence, every experience is a valuable tome.",
  "Dreams are like stars; you may never touch them, but if you follow them, they'll lead you to your destiny.",
  "Evolving is not becoming someone new, but remembering who you truly are.",
  "Your inner universe shapes your outer reality.",
  "Moments of pause are the bridges to profound insights.",
  "Be fearless in pursuit of what sets your soul on fire.",
  "Journeys are made richer not by the destinations but by the memories crafted.",
  "The universe doesn't make mistakes; every twist and turn has its purpose.",
  "Each heartbeat is a universe of possibilities, waiting to be explored.",
  "The most powerful magic is believing in oneself.",
  "In life's orchestra, play your note with authenticity and fervor.",
  "Dive deep, for the treasures of life reside in the depths.",
  "Life's echo is often louder than its shout.",
  "When the heart and the mind align, miracles happen.",
  "The moon reminds us that phases are a part of life's journey.",
  "Listen more to understand, and less to reply.",
  // ... [previous quotes]

  "In the cosmic dance of life, every step holds a purpose.",
  "Dreams are the soul's whispers, urging us to break free.",
  "Life's beauty is magnified when viewed through the lens of gratitude.",
  "We are not mere spectators of the universe, but its vibrant participants.",
  "Cherish the pauses, for they often breathe life into our busiest moments.",
  "Beyond the horizon of fears lie oceans of possibilities.",
  "The most powerful stories are often written in the ink of resilience.",
  "In the echo of silence, profound wisdom often speaks.",
  "Life is less about perfection and more about connection.",
  "Mountains of challenges mold valleys of character.",
  "Let the winds of change uplift your wings, not deter your flight.",
  "The universe pens its tales not in words, but in moments.",
  "In every heartbeat, there's a rhythm of life waiting to be danced.",
  "When you align with purpose, the universe aligns with you.",
  "The beauty of life lies not in avoiding storms but in dancing in the rain.",
  "Wonders often reside on the other side of wander.",
  "In the grand play of existence, embrace your unique role with fervor.",
  "Time doesn't wait; it teaches the art of prioritization.",
  "Every challenge surmounted adds a chapter to your saga of strength.",
  "Life is an enigmatic art painted with hues of choices.",
  "When we resonate with love, the world reflects it back.",
  "Let not your fears define you, but your dreams.",
  "The canvas of life is adorned by moments, both fleeting and eternal.",
  "Beyond the chaos, there's always a realm of harmony waiting to be discovered.",
  "Each of us is a star, radiating our unique light.",
  "Growth is not mere expansion, but deep-rooted evolution.",
  "The universe hums a song of unity; it's up to us to join the chorus.",
  "Seek not only to exist, but to experience and enrich.",
  "Life's greatest teacher is often the mirror of introspection.",
  "When you dive into the depths of the self, the universe reveals its treasures.",
  "Dreams are the seeds; actions, the water that allows them to flourish.",
  "When one door of opportunity closes, countless others await discovery.",
  "Life is a river, ever-flowing and ever-changing.",
  "Embrace the unknown; for therein lie the wonders yet explored.",
  "The melody of life is best enjoyed when sung with an open heart.",
  "In the theater of life, every act contributes to the grand finale.",
  "Let the footprints of your journey inspire others to tread their path.",
  // ... [previous quotes]

  "The tapestry of the cosmos is interwoven with threads of purpose.",
  "In the alchemy of existence, challenges often transmute into wisdom.",
  "Each moment is a brushstroke on the canvas of eternity.",
  "In the symphony of the cosmos, every heart is an essential note.",
  "The journey is as profound as the destination, if not more.",
  "Seek the whispers of the universe in the stillness of your heart.",
  "Dream with fervor, live with purpose, and cherish every unfolding chapter.",
  "The stars are not just above us, they are within us, guiding our way.",
  "Life's intricacies are best unraveled with patience and perspective.",
  "Every sunrise is a universe's invitation to embark on a new quest.",
  "The riddles of existence are often cloaked in the simplest of moments.",
  "Harbor not just dreams, but the courage to chase them relentlessly.",
  "Each of us is an echo of the infinite, resonating with purpose.",
  "In the book of time, every second is a precious word.",
  "Boundaries are but horizons waiting to be expanded.",
  "The essence of life is not in conquest, but in the journey of discovery.",
  "Every heartbeat is a silent symphony of unsung possibilities.",
  "Amidst life's storms, find the anchor of hope.",
  "The universe is not just vast space but endless opportunity.",
  "Life's rhythm is as much in the pauses as in the beats.",
  "Cherish memories; they're timeless treasures of the heart.",
  "Where purpose ignites, obstacles dissolve.",
  "Waves of change shape the shores of destiny.",
  "In the dance of destiny, grace lies in every step.",
  "The universe speaks in the language of moments; learn to listen.",
  "With a heart full of dreams, the universe becomes a playground of possibilities.",
  "Echoes of past choices shape the melodies of our present.",
  "In the orchestra of existence, harmony is achieved when we celebrate our differences.",
  "The art of life lies in seeing the extraordinary in the ordinary.",
  "Life is an enigma, and love, its most profound key.",
  "When we align with love, the universe conspires in our favor.",
  "Courage is the compass that guides us through uncharted territories.",
  "The journey of a thousand dreams begins with a single spark of passion.",
  "Beyond the horizon of doubts lie the lands of achievements.",
  "Where the heart leads, magic follows.",
  "In the cosmic canvas, every challenge is but a stroke of contrast enhancing the beauty.",
  // ... [previous quotes]

  "Beyond the veil of the known lies the allure of the unknown.",
  "In the grand theatre of life, every experience is a scene worth cherishing.",
  "When we dance to the tunes of the soul, the universe joins in.",
  "Moments in stillness often lead to epochs of inspiration.",
  "The beauty of the journey is in the landscapes of the soul we traverse.",
  "Every setback is a setup for a remarkable comeback.",
  "The whispers of the wind carry tales of timeless truths.",
  "Where curiosity thrives, barriers crumble.",
  "The richest treasures often lie in the simplest moments.",
  "To touch the sky, one doesn't need wings but dreams.",
  "Life is the art of drawing without an eraser, every line has its purpose.",
  "Amidst the cacophony, there's a melody waiting to be discovered.",
  "To sail the oceans of dreams, one must first dare to leave the shore.",
  "In the embrace of the cosmos, every atom dances with joy.",
  "Stories of resilience echo far longer than tales of despair.",
  "The heart's compass often points to the most cherished destinations.",
  "Mysteries of the universe unravel in the sanctuary of introspection.",
  "The spark of creativity is ignited in the crucible of challenges.",
  "When you voyage inwards, every discovery becomes a revelation.",
  "With roots of resolve and wings of aspiration, the sky isn't the limit.",
  "Life's tapestry is colored by the shades of our choices.",
  "In the quest for meaning, every step is a story.",
  "The finest symphonies are those orchestrated by the heart.",
  "Every challenge conquered is a mountain peak ascended.",
  "Where wonder wanders, realms of possibility unveil.",
  "Dance not to the tunes of time, but to the rhythm of the soul.",
  "To fathom the universe, dive into the depths of your consciousness.",
  "With every dusk, there's a dawn awaiting to write a new tale.",
  "Embrace the mystery, for therein lies the charm of existence.",
  "The melodies of memories linger, long after the moments have passed.",
  "In the palette of life, every emotion is a unique hue.",
  "Dreams nurtured in the heart find wings to fly.",
  "When intentions are pure, the universe carves paths of serendipity.",
  "Life is a dance of light and shadow, both essential to the painting.",
  "The echoes of authenticity resonate louder than shouts of pretense.",
  // ... [previous quotes]

  "In life's tapestry, each thread, no matter how thin, adds to the grand design.",
  "Embrace the mosaic of moments, for each piece adds to your masterpiece.",
  "The greatest adventures often lie on paths less trodden.",
  "In the silence between heartbeats, life's true essence speaks.",
  "Beyond the constraints of the mind lies the realm of endless possibilities.",
  "When the spirit soars, even the stars become stepping stones.",
  "The universe's melody resonates with those who dare to listen.",
  "Cherish the questions, for in them lie the seeds of wisdom.",
  "Each sunrise is a testament to the universe's undying hope in us.",
  "In the library of life, every experience is a chapter worth reading.",
  "Courage isn't just climbing peaks but also crossing valleys with hope.",
  "The heart knows a language deeper than words, the language of essence.",
  "In the kaleidoscope of existence, every perspective is a unique shade.",
  "When the spirit is aligned, destiny unveils its beautiful design.",
  "Dreams are the universe's way of sowing seeds of wonder in our hearts.",
  "In the dance of existence, every step, every twirl has its purpose.",
  "The universe is not a canvas of black and white, but a spectrum of colors waiting to be explored.",
  "With every challenge faced, the soul collects a gem of wisdom.",
  "Life's beauty isn't just in the destinations reached, but in the journeys undertaken.",
  "Echoes of authenticity often drown the noises of pretense.",
  "Where passion fuels the heart, impossibilities fade.",
  "Every droplet of kindness ripples across the vast oceans of existence.",
  "In the symphony of life, even the pauses carry profound meaning.",
  "Each star in the cosmos is a beacon of dreams realized.",
  "The finest stories often spring from the deepest scars.",
  "Where love resides, boundaries dissolve.",
  "In the quest for truth, every discovery shapes our essence.",
  "Dreams are the soul's compass, pointing to uncharted terrains.",
  "Every sunset paints a picture of hope, whispering promises of a new dawn.",
  "Challenges are life's way of sculpting our character to perfection.",
  "In the infinite cosmos, every moment is a blink of wonder.",
  "The heart's whispers often carry the wisdom of ages.",
  "Life is the grandest adventure, with every moment a step into the unknown.",
  "In the galaxy of existence, every soul is a radiant star.",
  "Embrace the chaos, for within it lie patterns of profound beauty.",
];
